language: java
services:
  - docker
jdk:
  - openjdk11
before_install:
  - mvn -B versions:set -DnewVersion=$TRAVIS_BRANCH
script:
  - mvn -B package
deploy:
  skip_cleanup: true
  provider: script
  script:
    bash .ci/tag.sh && docker build -t inseefrlab/onyxia-api:$DOCKER_TAG onyxia-api && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push inseefrlab/onyxia-api:$DOCKER_TAG
  on:
    branch: improve-ci
    tags: true
