package fr.insee.onyxia.model.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;

@JsonIgnoreProperties(ignoreUnknown = true)
@Schema(description = "Parameter for service creation")
public class CreateServiceDTO {
    @Schema(
            description = "Catalog where the package of the service is taken from.",
            defaultValue = "internal")
    String catalogId;

    @Schema(
            description =
                    "Helm package that will be used to create the service, necessary for package recovering (verify package)",
            required = true)
    String packageName;

    @Schema(description = "Version of the helm package, put version into creation, if not null")
    String packageVersion;

    @Schema(description = "A chosen name for the service, if null a name is generated by helm")
    String name;

    @Schema(description = "Content of values.yaml", required = true)
    Object options;

    @Schema(
            description = "When true, nothing is run (helm dry run mode), false by default",
            defaultValue = "false")
    boolean dryRun = false;

    @Schema(
            description = "When true, all users of the namespace will list this service, false by default",
            defaultValue = "false")
    boolean share = false;

    @Schema(description = "A friendly name for the service")
    String friendlyName;

    public String getCatalogId() {
        return catalogId;
    }

    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getPackageVersion() {
        return packageVersion;
    }

    public void setPackageVersion(String packageVersion) {
        this.packageVersion = packageVersion;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Object getOptions() {
        return options;
    }

    public void setOptions(Object options) {
        this.options = options;
    }

    public boolean isDryRun() {
        return dryRun;
    }

    public void setDryRun(boolean dryRun) {
        this.dryRun = dryRun;
    }

    public boolean isShare() {
        return share;
    }

    public void setShare(boolean share) {
        this.share = share;
    }

    public String getFriendlyName() {
        return friendlyName;
    }

    public void setName(String nafriendlyNameme) {
        this.friendlyName = friendlyName;
    }
}
